# Generated by Django 5.2.4 on 2025-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_cnpj_fundo', models.CharField(max_length=20, unique=True)),
                ('st_classe_fundo', models.CharField(max_length=100)),
                ('st_estrategia_fundo', models.TextField()),
                ('st_obs_fundo', models.TextField(blank=True, null=True)),
                ('relatorios', models.JSONField(default=list)),
                ('cod_quantum_fundomaster', models.CharField(blank=True, max_length=50, null=True)),
                ('st_cnpj_fundomaster', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
